<?php
/**
 * Created by PhpStorm.
 * User: stb216
 * Date: 14/02/18
 * Time: 12:31
 */
?>
<div id="filters">
    <div class="col-md-6">
        <form id="uplift" method="post" action="../Scripts/NewAdmin.php">
            <p class="bold">Set new Admin: </p>
            <label><input type="text" name="email" id="email"></label>
            <input type="submit" name="uplift" value="Make Admin">
        </form>
    </div>
    <div class="col-md-6">
        <form id="limit" method="post" action="../Scripts/SetAdExpire.php">
            <p class="bold">Set the time it takes for adverts to expire, in days: </p>
            <label><input type="number" name="expire" id="expire"></label>
            <input type="submit" name="expiry" value="Set Expiry Time">
        </form>
        <a href="../Scripts/ExpireAdvert.php"><button type="button">Expire old adverts.</button></a>
    </div>
</div>