<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Adverts</title>
</head>
<body>
<div id="introtext">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at feugiat ligula.
        Morbi pellentesque dignissim nibh sit amet cursus. Mauris eu euismod orci.
        Aenean in mauris vel sem interdum mollis. Etiam scelerisque ultricies odio vitae tempor.
        Donec dictum faucibus congue. Nulla at magna consectetur enim tempus elementum a sed ex.
        Etiam id pulvinar nulla. In vel turpis vitae neque rutrum auctor ut vitae sem. Etiam ut scelerisque lacus.
        Fusce nec urna ex. Morbi tincidunt justo non consectetur bibendum. Nunc sed lorem nec mauris dignissim ultricies sed eu odio.
        Mauris ut arcu eget tellus tempor suscipit.
    </p>
    <p>
        Suspendisse tincidunt ante ut maximus fermentum. Maecenas in volutpat nisl.
        Morbi ac sem sagittis, cursus mi nec, imperdiet est. Sed commodo erat justo, et euismod enim rutrum congue.
        Vivamus tellus mi, venenatis eget porttitor in, viverra sed sem. Interdum et malesuada fames ac ante ipsum primis in faucibus.
        Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
    </p>
</div>
<form action="../AdSearch.php" method="get" id="search">

    <?php
    include 'SearchBox.phtml';
    //We put the form for searching in a few pages, so let's write it once and include it.
    ?>

</form>