<div id="pages">
    <button form="search" type="submit" name="page"<?php echo 'value="'. ($page-1) . '"' ?>
    <?php if($page == 1){echo 'style="display:none"';} ?>><?php echo ($page-1)
        //There is no page 0, so we don't want it to show up.?></button>
    <button class="here"><?php echo $page
        //This one just shows what page the user is on. It's only a button for consistent styling?></button>
    <button form="search" type="submit" name="page"<?php echo 'value="'. ($page+1) . '"' ?>
        <?php if($capped == 1){echo 'style="display:none"';}
        //We don't want any buttons for a page over the maximum adcount.
        //So if the variable that denotes that the last ad was printed is 1,
        //We don't make another next page button. ?>><?php echo ($page+1) ?></button>
</div>