<?php
//These functions take the GET inputs from the url, and use them to refill
//The corresponding form inputs. This one is called in each text/number input
//o supply a value, but only if the GET value is set.
function fillInput($getVar){
    if(isset($_GET[$getVar])){
        echo 'value="' . $_GET[$getVar] . '"';
    }
}
//These two are used for specific parts which require slightly different approaches
function selected($selected){
    if($selected == $_GET['sort']){
        //Only one of sort values can be selected, and get['sort'] is one value
        //So this compares that to find out if any sort was set.
        echo "selected";
    }
}
function multiSelected($selected){
    if(in_array($selected, $_GET['colours'])){
        //Colours are stored in an array, so we need to check if the input value
        //Is in the array.
        echo "selected";
    }
}
?>

<script>
    function liveSearch(){
        var search = document.getElementById("adname").value;
        var formString = "../Scripts/LiveSearch.php?search=" + search;
        fetch(formString)
            .then(function (resp) {
                console.log(resp);
                return resp.json();
            })
    .then(function (resp) {

    })
}

</script>

<div id="filters">
    <p id="preface">Input your search criteria below to find matching ads, or just hit search to look through all of them:</p>
    <div class="col-lg-6">
        <div id="liveSearch">
        <label><p>Search by Ad name: </p><input type="text" name="adname" id="adname" <?php fillInput("adname") ?> oninput="liveSearch()"></label>
        </div>
        <label><p>Maximum Price: £</p><input type="number" name="maxprice" id="maxprice" <?php fillInput("maxprice") ?>></label>
        <label><p>Minimum Price: £</p><input type="number" name="minprice" id="minprice" <?php fillInput("minprice") ?>></label>
    </div>
    <div class="col-lg-6" id="right">
        <label><p>Say where you're looking: </p><input type="text" name="location" id="location" <?php fillInput("location") ?>></label>
        <label><p>Pick the colours that you want to see: <br>(Hold ctrl to select multiple)<br>Defaults to all colours </p><select multiple name="colours[]" id="colours">
            <option value="Black" <?php multiSelected("Black"); ?>>Black</option>
            <option value="White" <?php multiSelected("White"); ?>>White</option>
            <option value="Red" <?php multiSelected("Red"); ?>>Red</option>
            <option value="Blue" <?php multiSelected("Blue"); ?>>Blue</option>
            <option value="Green" <?php multiSelected("Green"); ?>>Green</option>
        </select></label>
        <label><p>Sort by: </p><select name="sort">
            <option value="AgeA" <?php selected("AgeA"); ?>>Age: Newest first</option>
            <option value="AgeD" <?php selected("AgeD"); ?>>Age: Oldest first</option>
            <option value="PriceA" <?php selected("PriceA"); ?>>Price: Ascending</option>
            <option value="PriceD" <?php selected("PriceD"); ?>>Price: Descending</option>
            <option value="Name" <?php selected("Name"); ?>>Name: Alphabetical</option>
        </select></label>
        <label><input type="submit" name="submit" value="Search"></label>
    </div>
</div>

